version: "3.8"
services:
  rvc:
    image: rvc:latest
    container_name: voice2
    stdin_open: true
    tty: true
    command: /bin/bash
    shm_size: '8gb'
    volumes:
      - .:/app
      # - ./weights:/app/assets/weights
      # - ./opt:/app/opt
      # - ./dataset:/app/dataset # you can use this folder in order to provide your dataset for model training
    ports:
      - 8080:7865
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
