services:
  rvc:
    build:
      context: .
      dockerfile: Dockerfile
    image: rvc:latest
    container_name: rvc
    stdin_open: true
    tty: true
    command: /bin/bash
    shm_size: '8gb'
    volumes:
      - .:/app
    ports:
      - 7865:7865
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
